  {% set version = "1.0.1" %}

package:
  name: spacerplacer       # Name of your package
  version: {{ version }}      # Version of your package

source:
  url: https://github.com/fbaumdicker/SpacerPlacer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7ef9404d019cbd1f19c70f3fa45827d8351393c5
#  git_url: https://github.com/fbaumdicker/SpacerPlacer.git
#  git_rev: main
#  path: ../../spacerplacer/SpacerPlacer            # Path to the source files of your project
#  include:
#      - /additional_data/0_lh/*
#      - /mafft_scripts/*
#      - /*.py

channels:
  - conda-forge
  - bioconda
  - defaults

build:
  noarch: python
#  script: python setup.py install
  number: 0
  run_exports:
    - {{ pin_subpackage('spacerplacer', max_pin="x") }}


requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.21.4
    - pandas >=1.3.4
    - seaborn >=0.11.2
    - matplotlib-base >=3.4.3
    - scipy >=1.7.1
    - ete3 >=3.1.2
    - palettable >=3.3.0
    - graphviz >=0.20.1
    - sympy >=1.11.1
    - mafft >=7.490
    - biopython >=1.79
    - python-graphviz >=0.17
    - dill >=0.3.5.1

about:
  home: https://github.com/fbaumdicker/SpacerPlacer  # URL for the project
  license: GPL 3.0                              # License for your package
  license_file: LICENSE
  summary: "SpacerPlacer is a powerful software for reconstructing ancestral CRISPR spacer arrays."

test:
  imports:
    - spacerplacer
    - sp_model
  commands:
    - spacerplacer -h
